### PR TITLE
Attempt at 0.11.1

### PR DESCRIPTION
**Pull request by unquietwiki**
Hey @ajacksified . I've been working on an [upgraded version of Floorplan](https://github.com/unquietwiki/floorplan), and think I might have hit some stumbling block with using the current MediatorJS. I decided to poke around the code, and ended up cleaning up the unit tests & better-enabling use of this with ES2015 & later codebases. Interestingly enough, the tests have more failures against the non-babel-minified version, than that one (which has only one failure atm).

Thanks!

### CODE REVIEW

**Comment by unquietwiki** [comment]
Specifically, the test failing is the "should update subscriber by fn" one.

**Comment by ajacksified** [comment]
Cool. No big deal if not, I can just run `eslint --fix` myself, but it makes it easier to view on github. 🤷‍♀️

**Comment by unquietwiki** [comment]
(ponders) In my other project, I'm using different .eslintrc to manage
checks there. I think could modify that approach for you in a bit; unless
you're doing stuff already.

**Comment by unquietwiki** [comment]
@ajacksified I fixed the semicolons! ⌨️ Also tried to fix the travis test, and supply a gzipped file.

**Comment by unquietwiki** [comment]
Hey @ajacksified I dunno if you had a chance to look at this. Whenever you do, could you please also look at how this is being used in https://github.com/unquietwiki/floorplan/tree/master/src/scripts/client ? You're better at this stuff than I am! 🥇

**Comment by unquietwiki** [comment]
Hey @ajacksified I was closing out stale pull requests, and saw this one was open. Did you have time for this, or should I delete it? Thanks.

**Comment by unquietwiki** [comment]
Closing PR: it's been over a year, and I agree the steps can be broken down better.

**Pull request closed without merging**
